name: Pau_Ejercicio-1
 
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Mensaje que muestra'
        required: true
        default: 'Hola buenas si'
jobs:
  job1:
    name: trabajo 1
    runs-on: ubuntu-latest
    steps:
      - name: paso 1
        run: |
          echo "${{github.event.inputs.message}}"
      - name: paso 2
        run: |
          echo Permitame que insista: "${{github.event.inputs.message}}"
